[project]
name = "code-packager"
version = "0.2.0"
description = "Easily zip your codebase while excluding unnecessary files like a pro! Say goodbye to bloated archives and hello to clean, lightweight packages. 🎉"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "DealiAxy", email = "dealiaxy@gmail.com"},
]
dependencies = [
    "loguru>=0.7.3",
    "pathspec>=0.12.1",
    "textual>=0.70.0",
]

[project.scripts]
pack-my-code = "code_packager.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
